SELECT P.MEMBER_NAME,R.REVIEW_TEXT,DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d')AS REVIEW_DATE
FROM MEMBER_PROFILE AS P
JOIN REST_REVIEW AS R ON P.MEMBER_ID=R.MEMBER_ID
WHERE (R.MEMBER_ID) =(SELECT MEMBER_ID
                     FROM REST_REVIEW
                      GROUP BY MEMBER_ID
                     ORDER BY COUNT(*)DESC
                     LIMIT 1)
ORDER BY R.REVIEW_DATE,R.REVIEW_TEXT
